// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/ewallet_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ewallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XRev    string         `protobuf:"bytes,2,opt,name=_rev,json=Rev,proto3" json:"_rev,omitempty"`
	Balance float64        `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Get     []*Transaction `protobuf:"bytes,4,rep,name=get,proto3" json:"get,omitempty"`
	Send    []*Transaction `protobuf:"bytes,5,rep,name=send,proto3" json:"send,omitempty"`
}

func (x *Ewallet) Reset() {
	*x = Ewallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ewallet_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ewallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ewallet) ProtoMessage() {}

func (x *Ewallet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ewallet_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ewallet.ProtoReflect.Descriptor instead.
func (*Ewallet) Descriptor() ([]byte, []int) {
	return file_proto_ewallet_message_proto_rawDescGZIP(), []int{0}
}

func (x *Ewallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ewallet) GetXRev() string {
	if x != nil {
		return x.XRev
	}
	return ""
}

func (x *Ewallet) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Ewallet) GetGet() []*Transaction {
	if x != nil {
		return x.Get
	}
	return nil
}

func (x *Ewallet) GetSend() []*Transaction {
	if x != nil {
		return x.Send
	}
	return nil
}

var File_proto_ewallet_message_proto protoreflect.FileDescriptor

var file_proto_ewallet_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88,
	0x01, 0x0a, 0x07, 0x45, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x11, 0x0a, 0x04, 0x5f, 0x72,
	0x65, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x65, 0x76, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x03, 0x67, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ewallet_message_proto_rawDescOnce sync.Once
	file_proto_ewallet_message_proto_rawDescData = file_proto_ewallet_message_proto_rawDesc
)

func file_proto_ewallet_message_proto_rawDescGZIP() []byte {
	file_proto_ewallet_message_proto_rawDescOnce.Do(func() {
		file_proto_ewallet_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ewallet_message_proto_rawDescData)
	})
	return file_proto_ewallet_message_proto_rawDescData
}

var file_proto_ewallet_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ewallet_message_proto_goTypes = []interface{}{
	(*Ewallet)(nil),     // 0: Ewallet
	(*Transaction)(nil), // 1: Transaction
}
var file_proto_ewallet_message_proto_depIdxs = []int32{
	1, // 0: Ewallet.get:type_name -> Transaction
	1, // 1: Ewallet.send:type_name -> Transaction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ewallet_message_proto_init() }
func file_proto_ewallet_message_proto_init() {
	if File_proto_ewallet_message_proto != nil {
		return
	}
	file_proto_transaction_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_ewallet_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ewallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ewallet_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ewallet_message_proto_goTypes,
		DependencyIndexes: file_proto_ewallet_message_proto_depIdxs,
		MessageInfos:      file_proto_ewallet_message_proto_msgTypes,
	}.Build()
	File_proto_ewallet_message_proto = out.File
	file_proto_ewallet_message_proto_rawDesc = nil
	file_proto_ewallet_message_proto_goTypes = nil
	file_proto_ewallet_message_proto_depIdxs = nil
}
