// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/ewallet_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEwalletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ewallet *Ewallet `protobuf:"bytes,1,opt,name=ewallet,proto3" json:"ewallet,omitempty"`
}

func (x *CreateEwalletRequest) Reset() {
	*x = CreateEwalletRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ewallet_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEwalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEwalletRequest) ProtoMessage() {}

func (x *CreateEwalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ewallet_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEwalletRequest.ProtoReflect.Descriptor instead.
func (*CreateEwalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_ewallet_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEwalletRequest) GetEwallet() *Ewallet {
	if x != nil {
		return x.Ewallet
	}
	return nil
}

type CreateEwalletResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateEwalletResponse) Reset() {
	*x = CreateEwalletResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ewallet_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEwalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEwalletResponse) ProtoMessage() {}

func (x *CreateEwalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ewallet_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEwalletResponse.ProtoReflect.Descriptor instead.
func (*CreateEwalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_ewallet_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEwalletResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ewallet_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ewallet_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_proto_ewallet_service_proto_rawDescGZIP(), []int{2}
}

func (x *SendRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ewallet_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ewallet_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_proto_ewallet_service_proto_rawDescGZIP(), []int{3}
}

func (x *SendResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetlastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key bool `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetlastRequest) Reset() {
	*x = GetlastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ewallet_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetlastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetlastRequest) ProtoMessage() {}

func (x *GetlastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ewallet_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetlastRequest.ProtoReflect.Descriptor instead.
func (*GetlastRequest) Descriptor() ([]byte, []int) {
	return file_proto_ewallet_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetlastRequest) GetKey() bool {
	if x != nil {
		return x.Key
	}
	return false
}

type GetlastResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonData string `protobuf:"bytes,1,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
}

func (x *GetlastResponse) Reset() {
	*x = GetlastResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ewallet_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetlastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetlastResponse) ProtoMessage() {}

func (x *GetlastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ewallet_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetlastResponse.ProtoReflect.Descriptor instead.
func (*GetlastResponse) Descriptor() ([]byte, []int) {
	return file_proto_ewallet_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetlastResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

var File_proto_ewallet_service_proto protoreflect.FileDescriptor

var file_proto_ewallet_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x45, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x07,
	0x65, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3d, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2e, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x26, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x6c, 0x61,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2d, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x32, 0xa9, 0x01, 0x0a, 0x0e, 0x45,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x15,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x25, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x0c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x6c, 0x61, 0x73,
	0x74, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ewallet_service_proto_rawDescOnce sync.Once
	file_proto_ewallet_service_proto_rawDescData = file_proto_ewallet_service_proto_rawDesc
)

func file_proto_ewallet_service_proto_rawDescGZIP() []byte {
	file_proto_ewallet_service_proto_rawDescOnce.Do(func() {
		file_proto_ewallet_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ewallet_service_proto_rawDescData)
	})
	return file_proto_ewallet_service_proto_rawDescData
}

var file_proto_ewallet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ewallet_service_proto_goTypes = []interface{}{
	(*CreateEwalletRequest)(nil),  // 0: CreateEwalletRequest
	(*CreateEwalletResponse)(nil), // 1: CreateEwalletResponse
	(*SendRequest)(nil),           // 2: SendRequest
	(*SendResponse)(nil),          // 3: SendResponse
	(*GetlastRequest)(nil),        // 4: GetlastRequest
	(*GetlastResponse)(nil),       // 5: GetlastResponse
	(*Ewallet)(nil),               // 6: Ewallet
	(*Transaction)(nil),           // 7: Transaction
}
var file_proto_ewallet_service_proto_depIdxs = []int32{
	6, // 0: CreateEwalletRequest.ewallet:type_name -> Ewallet
	7, // 1: SendRequest.transaction:type_name -> Transaction
	0, // 2: EwalletService.CreateEwallet:input_type -> CreateEwalletRequest
	2, // 3: EwalletService.Send:input_type -> SendRequest
	4, // 4: EwalletService.Getlast:input_type -> GetlastRequest
	1, // 5: EwalletService.CreateEwallet:output_type -> CreateEwalletResponse
	3, // 6: EwalletService.Send:output_type -> SendResponse
	5, // 7: EwalletService.Getlast:output_type -> GetlastResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ewallet_service_proto_init() }
func file_proto_ewallet_service_proto_init() {
	if File_proto_ewallet_service_proto != nil {
		return
	}
	file_proto_ewallet_message_proto_init()
	file_proto_transaction_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_ewallet_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEwalletRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ewallet_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEwalletResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ewallet_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ewallet_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ewallet_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetlastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ewallet_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetlastResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ewallet_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ewallet_service_proto_goTypes,
		DependencyIndexes: file_proto_ewallet_service_proto_depIdxs,
		MessageInfos:      file_proto_ewallet_service_proto_msgTypes,
	}.Build()
	File_proto_ewallet_service_proto = out.File
	file_proto_ewallet_service_proto_rawDesc = nil
	file_proto_ewallet_service_proto_goTypes = nil
	file_proto_ewallet_service_proto_depIdxs = nil
}
